# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 946c5846c805cc63bf9d7723c5698b80feed26916c871f808cf9d31493a24eb61693228d68125f84c9b059f4f47d9aaa9ced805c9be511fafe92aeaaae41b035

test:
  secret_key_base: 85fce370b50376fc854470ec651fd349dabe460c0c53998edce0d7915f0b7fcf73e0707761cb9bbfeb4e82977e36b7ed4cb452988c895fb34c13bb8014a201b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
